import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import NextAuthProvider from '../components/NextAuthProvider'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-slate-700 mx-20 font-bold" >
          <Link href="/" className="mx-6">Home</Link>
          <Link href="/frontend/register" className="mx-6">Register</Link>
          <Link href="/frontend/dashboard" className="mx-6">Dashboard</Link>
          <Link href="/frontend/login" className="mx-6">Login</Link>
        </div>
          <NextAuthProvider>
            {children}  
          </NextAuthProvider>
            
      </body>
    </html>
  );
}
